#!/usr/bin/env node
'use strict';

const fs = require('fs');

let basePath = process.cwd();

let [, , oldName, newName] = process.argv;

if(oldName && newName) {
    if (oldName.indexOf('@') !== -1) {
        oldName = oldName.split('@')[0];
    }
    if (oldName.indexOf('.') !== -1) {
        oldName = oldName.split('.')[0];
    }
    for (let i = 1; i < 4; i++) {
        let oldFileName = i>1? `${oldName}@${i}x.png` : `${oldName}.png`;
        let newFileName = i>1? `${newName}@${i}x.png` : `${newName}.png`;
        let oldPath = `${basePath}/${oldFileName}`;
        let newPath = `${basePath}/${newFileName}`;
        fs.rename(oldPath,newPath,(err)=> {
            if(err) {
                console.error(err);
            }
            else {
                console.log(`${oldFileName}重命名为${newFileName}`)
            }
        })
    }
}
else{
    console.log('请输入文件名');
}
